spring:
  flyway:
    validate-on-migrate: false
  datasource:
    url: jdbc:mysql://localhost:3306/agencia_sanguinea?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    root: INFO
    br.com.dev: DEBUG
    org.springframework.web: ERROR
    org.hibernate: ERROR